# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  sample:
    jobs:
      - node/test:
          version: '15.1'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
  test-deploy:
    jobs: 
     # - build-project
      - build-front

jobs:
  build-project:
    docker:
      - image: cimg/node:16.4.0
    steps:
      - checkout
      - run: node --version
      - run: ls    
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      # - run: npm run build
  build-front:
    docker:
     - image: cimg/node:16.4.0
    steps:
     - checkout
     - run: cd frontend/graph-path && npm install && npm test && npm run build
    #  - run: ls 
    #  - run: 
    #     name: Install front Dependencies
    #     command: npm install
    #  - run:
    #     name: Build front app
    #     command: yarn build
